name: Static Analysis

on:
  pull_request:
    branches: main

jobs:
  lint_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -f cppcheck python3 cmake g++ git
      - name: Build Clang
        run: |
          PROJ_DIR=`pwd`
          mkdir /llvm
          cd /llvm
          git clone --depth=1 https://github.com/llvm/llvm-project.git
          cd llvm-project
          mkdir build
          cd build
          cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../llvm
          make
          cd bin
          export PATH=$PATH:`pwd`
          cd $PROJ_DIR
        
  linting:
    needs: lint_setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: |
          cppcheck .
          scan-build -o logs g++ main.cpp -std=c++17 -Wall -Wextra -Werror -o firstIO