name: Static Analysis

on:
  pull_request:
    branches: main

jobs:
  lint_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -f cppcheck python3 cmake g++
        
  linting:
    needs: lint_setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: |
          cppcheck .